apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rdv-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/M4STERPIECE77K/MED-MANAGE.git # Replace with your actual repo URL if different
    targetRevision: develop
    path: backend/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: rdv
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
