apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - secrets.yaml
  - postgres.yaml
  - fastapi.yaml
  - spring-boot.yaml

configMapGenerator:
  - name: rdv-db-init
    files:
      - ../scripts/sql/v1_schema.sql
      - ../scripts/sql/v2_table.sql
