services:
  db:
    image: postgres:15-alpine
    container_name: rdv-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U masterpiece -d rdv_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi-backend:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: rdv-fastapi-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

networks:
  default:
    name: rdv-network
