apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rdv-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/M4STERPIECE77K/MED-MANAGE.git
    targetRevision: HEAD
    path: backend/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: rdv
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
